### ISSUE TITLE
Found this repo via a Youtube comment on lambda

### ISSUE THREAD

**Issue by snepraj2709** [sukhchainn/contact#2]
connect me on my mail- snehaprajapatijnv15@gmail.com
I am working on a video platform web application, let's chat if you find the idea interesting.

**Comment by sukhchainn** [comment]
Let's continue in the discussions here. I want to know what it's about and what are your visions of it?

**Comment by snepraj2709** [comment]
Its a Video based platform to find a little likeminded community or group
in a live manner, you can say clubhouse with video facility added.

**Comment by sukhchainn** [comment]
It's interesting, but what do you plan on using videos as? What technologies do you think will solve this problem? Do you have a plan on how we are going to do about it?

**Comment by snepraj2709** [comment]
Obviously its there to connect people in a more real manner, I tried using Jitsi to integrate video calls, but its limited to some 5- people and only 1 group can connect at a time.

**Comment by sukhchainn** [comment]
what do you mean by real manner can you explain that?

If we start a video call then would it be in real manner?
